name: Dependabot Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: test
      run: |
        ./gradlew test
