name: Java CI with Gradle

on:
  push:
    branches:
      - java17

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN_GIT }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run everything
      run: |
        sh run-everything
        cd output
        ./toMd.sh ../index.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: result adding back to repo [skip ci]
